language: c
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran openmpi-bin libopenmpi-dev

install: true

script:
  - make clean
  - export FLOW_TYPE=TGV
  - make
  - mpirun -n 1 ./incompact3d
